server:
  port: 8088 # 게이트웨이 실행 포트

spring:
  main:
    web-application-type: servlet
  application:
    name: golden-harvest-auth
  profiles:
    active: local

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  datasource:
    url: jdbc:mariadb://${AMAZON_RDS}:3306/goldenharvest
    username: admin
    password: harvest123
    driver-class-name: org.mariadb.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiration: 3600000     # 1시간
  refresh-token-expiration: 1209600000 # 14일
aws:
  s3:
    bucket: goldenharvest-bucket
    region: ap-northeast-2
    base-url: https://goldenharvest-bucket.s3.ap-northeast-2.amazonaws.com/uploads/
  credentials:
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}
file:
  upload-dir: ./uploads

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.servlet: DEBUG
    org.springframework.web.servlet.mvc.method.annotation: TRACE
    org.springframework.http: DEBUG
    org.springframework.http.converter: TRACE
