spring:
  application:
    name: golden-harvest-gateway # 게이트웨이 애플리케이션 이름
  profiles:
    active: local

  # Kafka Producer 설정
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092} # Kafka 서버 주소
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  datasource:
    url: jdbc:mariadb://${AMAZON_RDS}:3306/goldenharvest
    username: admin
    password: harvest123
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 8
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 300000
      max-lifetime: 1800000
      leak-detection-threshold: 20000
      pool-name: goldenharvest-hikari-gateway

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

file:
  upload-dir: ./uploads

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/**/*.xml

kamis:
  cert:
    key: ${KAMIS_CERT_KEY}
    id: ${KAMIS_CERT_ID}

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiration: 3600000    # 1시간
  refresh-token-expiration: 1209600000 # 14일

server:
  port: 8000 # 게이트웨이 실행 포트

inventory:
  base-url: http://localhost:8088

aws:
  s3:
    bucket: goldenharvest-bucket
    region: ap-northeast-2
    base-url: https://goldenharvest-bucket.s3.ap-northeast-2.amazonaws.com/uploads/
  credentials:
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}